### ISSUE TITLE
Compiler confusion on jvmLoadString()+DoNothing/Drop+jvmLoadString().

### ISSUE THREAD

**Issue by XerTheSquirrel** [SquirrelJME/SquirrelJME#22]
Using compiler generated `jvmLoadString()` and then either doing nothing (just assigning it to a variable) or calling `Assembly.objectToPointer(str)` on it, followed by another `jvmLoadString()` makes the value for a function call incorrect as it confuses the compiler.

In Fossil checkout:

```
repository:   /home/stephanie/squirreljme/../squirreljme.fossil
local-root:   /home/stephanie/squirreljme/
config-db:    /home/stephanie/.fossil
checkout:     e77018c3eaf4037377542b8b5d04ff62b7e52e28 2019-06-14 15:37:53 UTC
parent:       895f1a5e6bc724ba43736633e296d08756980c16 2019-06-14 15:01:44 UTC
tags:         trunk
comment:      Add configuration ROM to RatufaCoat; Correct potential memory leak in RatufaCoat; Implement Java instruction write
              types in RatufaCoat (user: stephanie.gawroriski)
```

Java code:

```Java
/**
	* Entry point for the bootstrap.
	*
	* @param __rambase The base RAM address.
	* @param __ramsize The size of RAM.
	* @param __rombase Base address of the ROM (for offset calculation).
	* @param __romsize The size of ROM.
	* @param __confbase The configuration memory base.
	* @param __confsize The configuration memory size.
	* @since 2019/05/25
	*/
static final void __start(int __rambase, int __ramsize,
	int __rombase, int __romsize, int __confbase, int __confsize)
{
	// Initialize the RAM links to setup dirty bits and initialize the
	// last block of memory with anything that remains. This makes it so
	// the RAM is actually useable.
	Allocator.__initRamLinks(__rambase, __ramsize);
	
	// Test
	todo.DEBUG.code('S', 'T', Assembly.objectToPointer("Hello?"));
	
	// Debug
	todo.DEBUG.note("Hello adorable and cute squirrels!");
	todo.DEBUG.note("Basic formatting too: %s!", "Neat!");
	
	Assembly.breakpoint();
	throw new todo.TODO();
}
```

Results in:

```
Al 0000001e    // Allocate length
Ap 00104960   // Allocation pointer
NA 00104960  // New array pointer
Al 00000020
Ap 00104988 // String "Hello?"
NE 00104988 // New instance pointer for String "Hello?"
Nc 00100c1c  // New instance class: String:
Al 00000024
Ap 001049b0
NA 001049b0
GC 00104960 // Garbage collect pointer
Ga 00000001 // Garbage collected array
Af 00104960 // Allocation free
Al 0000003a
Ap 001049dc
NA 001049dc
Al 00000020
Ap 00104960
NE 00104960
Nc 00100c1c
Al 0000005c
Ap 00104a20
NA 00104a20
GC 001049dc
Ga 00000001
Af 001049dc
Al 00000018
Ap 00104960
NA 00104960  // todo.DEBUG.note's __args (before call)
Nf 00104960   // todo.DEBUG.note's __fmt (within DEBUG.note)
Na 00104960  // todo.DEBUG.note's __args (within DEBUG.note)
Call trace:
    <unknown>.<unknown> @1005E4h (:0 J0@0)
    todo/DEBUG.note:(Ljava/lang/String;[Ljava/lang/Object;)V @4F100E91h (:90 J182@46)
    cc/squirreljme/jvm/Bootstrap.__start:(IIIIII)V @4F1154C7h (:52 J184@15)

Exception in thread "main" cc.squirreljme.vm.VMException: AE09 <unknown>.<unknown> @1005E4h (:0 J0@0)
        at cc.squirreljme.vm.summercoat.NativeCPU.run(NativeCPU.java:184)
        at cc.squirreljme.vm.summercoat.NativeCPU.run(NativeCPU.java:155)
        at cc.squirreljme.vm.summercoat.SummerCoatFactory.createVM(SummerCoatFactory.java:362)
        at cc.squirreljme.vm.VMFactory.main(VMFactory.java:226)
        at cc.squirreljme.builder.support.vm.VMMain.main(VMMain.java:163)
        at cc.squirreljme.builder.support.BuilderFactory.launch(BuilderFactory.java:325)
        at cc.squirreljme.builder.support.BuilderFactory.run(BuilderFactory.java:468)
        at cc.squirreljme.builder.entry.BuilderMain.main(BuilderMain.java:39)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at cc.squirreljme.runtime.javase.Main.main(Main.java:175)
Caused by: cc.squirreljme.vm.VMException: AE0a 66
        at cc.squirreljme.vm.summercoat.NativeCPU.runWithoutCatch(NativeCPU.java:306)
        at cc.squirreljme.vm.summercoat.NativeCPU.run(NativeCPU.java:168)
        ... 12 more
```

Code comparison dump:

```
    L  49   :   String qx = "Hello?";
    >N@  8: DEBUG_POINT:[49, 18, 5]              <=>J@  5: @5#LDC~:[Hello?]                     <
    >N@  9: LOAD_POOL:[Hello?, 23]               <|
    >N@ 10: LOAD_POOL:[STATIC+cc/squirreljme/jvm/<|
     JVMFunction::jvmLoadString(I)Ljava/lang/Stri |
     ng;, 24]                                     |
    >N@ 11: LOAD_POOL:[cc/squirreljme/jvm/JVMFunc<|
     tion, 7]                                     |
    >N@ 12: INVOKE:[24, R[23]]                   <|
    >N@ 13: COPY:[1, 15]                         <|
    >N@ 14: DEBUG_POINT:[49, 58, 7]              <=>J@  7: @7#ASTORE~:[6]                       <
    >N@ 15: IF_ICMP_EQUALS:[15, 0, ->@17]        <|
    >N@ 16: ATOMIC_INT_INCREMENT:[15, 4]         <|
    >N@ 17: COPY:[15, 14]                        <|
    L  52   :   todo.DEBUG.note("Hello adorable and cute squirrels!");
    >N@ 18: DEBUG_POINT:[52, 18, 9]              <=>J@  9: @9#LDC~:[Hello adorable and cute squi<
                                                  |>rrels!]                                     <
    >N@ 19: LOAD_POOL:[Hello adorable and cute sq<|
     uirrels!, 23]                                |
    >N@ 20: LOAD_POOL:[STATIC+cc/squirreljme/jvm/<|
     JVMFunction::jvmLoadString(I)Ljava/lang/Stri |
     ng;, 24]                                     |
    >N@ 21: LOAD_POOL:[cc/squirreljme/jvm/JVMFunc<|
     tion, 7]                                     |
    >N@ 22: INVOKE:[24, R[23]]                   <|
    >N@ 23: COPY:[1, 15]                         <|
    >N@ 24: DEBUG_POINT:[52, 3, 11]              <=>J@ 11: @11#ICONST_0~:[]                     <
    >N@ 25: INTEGER_OR_CONST:[0, 0, 16]          <|
    >N@ 26: DEBUG_POINT:[52, 189, 12]            <=>J@ 12: @12#ANEWARRAY~:[java/lang/Object]    <
    >N@ 27: LOAD_POOL:[[Ljava/lang/Object;, 23]  <|
    >N@ 28: LOAD_POOL:[STATIC+cc/squirreljme/jvm/<|
     JVMFunction::jvmNewArray(II)I, 24]           |
    >N@ 29: LOAD_POOL:[cc/squirreljme/jvm/JVMFunc<|
     tion, 7]                                     |
    >N@ 30: INVOKE:[24, R[23, 16]]               <|
    >N@ 31: COPY:[1, 16]                         <|
    >N@ 32: IF_ICMP_NOT_EQUALS:[3, 0, ->@214]    <|
    >N@ 33: DEBUG_POINT:[52, 184, 15]            <=>J@ 15: @15#INVOKESTATIC~:[method todo/DEBUG:<
                                                  |>:note(Ljava/lang/String;[Ljava/lang/Object;)<
                                                  |>V]                                          <
    >N@ 34: COPY:[16, 23]                        <|
    >N@ 35: LOAD_POOL:[STATIC+todo/DEBUG::note(Lj<|
     ava/lang/String;[Ljava/lang/Object;)V, 24]   |
    >N@ 36: LOAD_POOL:[todo/DEBUG, 7]            <|
    >N@ 37: INVOKE:[24, R[15, 16]]               <|
    >N@ 38: IF_ICMP_EQUALS:[23, 0, ->@44]        <|
    >N@ 39: ATOMIC_INT_DECREMENT_AND_GET:[24, 23,<|
      4]                                          |
    >N@ 40: IF_ICMP_NOT_EQUALS:[24, 0, ->@44]    <|
    >N@ 41: LOAD_POOL:[STATIC+cc/squirreljme/jvm/<|
     JVMFunction::jvmGarbageCollectObject(I)V, 25 |
     ]                                            |
    >N@ 42: LOAD_POOL:[cc/squirreljme/jvm/JVMFunc<|
     tion, 7]                                     |
    >N@ 43: INVOKE:[25, R[23]]                   <|
    >N@ 44: IF_ICMP_NOT_EQUALS:[3, 0, ->@220]    <|
    L  53   :   todo.DEBUG.note("Basic formatting too: %s!", "Neat!");
    >N@ 45: DEBUG_POINT:[53, 18, 18]             <=>J@ 18: @18#LDC~:[Basic formatting too: %s!] <
    >N@ 46: LOAD_POOL:[Basic formatting too: %s!,<|
```

**Comment by XerTheSquirrel** [comment]
So order of things in that snap:

 * `jvmLoadString("Hello?")` -> R15
 * Count up R15
 * `(ASTORE 6)`, R14 <- R15
 * `jvmLoadString("Hello adorable.....")` -> R15
 * `new Object[0]` -> R16
 * `todo.DEBUG.note(R15, R16)`

So `jvmLoadString()` might be returning the wrong value, since it does a `new String(bytes).intern()`.

But the following call to print the other message works fine. So maybe with discarded values it messes with reference counting?

**Comment by XerTheSquirrel** [comment]
Closing, this was caused by the allocation code not marking non-split chunks as used.
