### ISSUE TITLE
AOT Compilation fails for shaded JAR

### ISSUE THREAD

**Issue by XerTheSquirrel** [SquirrelJME/SquirrelJME#5]
Performing AOT compilation on the shaded JAR does not work because it seems that the shaded directory layout is picked for classes. Fixing may require a dash in the path or changing the extension of class files.

```
stephanie@oaktree:/tmp/sx$ jaotc squirreljme-javase.jar 
Error: java.lang.NoClassDefFoundError: net/multiphasicapps/zip/streamwriter/__TOCEntry__ (wrong name: __squirreljme/zip/net/multiphasicapps/zip/streamwriter/__TOCEntry__)
java.lang.NullPointerException
        at jdk.aot@11.0.1/jdk.tools.jaotc.Main.run(Main.java:136)
        at jdk.aot@11.0.1/jdk.tools.jaotc.Main.run(Main.java:102)
        at jdk.aot@11.0.1/jdk.tools.jaotc.Main.main(Main.java:81)
```

**Comment by XerTheSquirrel** [comment]
This fails regardless of whether or not there is a dash, so the contained files will need to be mangled.

**Comment by XerTheSquirrel** [comment]
Shaded JARs no longer being used with the modern Gradle stuff, so closing this now.
