### ISSUE TITLE
Gradius (Konami Mobile US) does not work

### ISSUE THREAD

**Issue by XerTheSquirrel** [SquirrelJME/SquirrelJME#56]
This is software has a number of quirks and incorrectness that will make it not work with standard conforming virtual machines. From what I have heard, this JAR was intended to be a demo that ran on the Konami website.

I have observed it doing the following:

 * Uses `1.0` for `microedition-configuration` and `2.0` for `microedition-profile`. These are version only things and it should be `CLDC-1.0` and `MIDP-2.0`.
 * It performs a `platformRequest("hjoja")`, not sure what this does but it likely activates something. 
   * If `false` is returned then `MIDletStateChangeException` is thrown.
   * Otherwise it will continue execution. It should be noted that if `true` IS returned then the application must exit before the request can be made. But the game just continues at this point, normally though `ConnectionNotFoundException` is thrown if it is not supported.

Issues with SquirrelJME: #55

**Comment by XerTheSquirrel** [comment]
Note that the game runs too slow in SpringCoat and it triggers the "too slow" message:

```
BK2c
Thread #3: SpringCoat-LCDUIThread
    at javax/microedition/lcdui/Image.getRGB:([IIIIIII)V @ 258 [IINC] (Image.java:205)
    at cc/squirreljme/runtime/lcdui/gfx/SerializedGraphics.drawRegion:(Ljavax/microedition/lcdui/Image;IIIIIIIIII)V @ 39 [INVO
KEVIRTUAL] (SerializedGraphics.java:213)
    at cc/squirreljme/runtime/lcdui/gfx/SerializedGraphics.drawRegion:(Ljavax/microedition/lcdui/Image;IIIIIIII)V @ 34 [INVOKEVIRTUAL] (SerializedGraphics.java:193)
    at cc/squirreljme/runtime/lcdui/gfx/EnforcedDrawingAreaGraphics.drawRegion:(Ljavax/microedition/lcdui/Image;IIIIIIII)V @ 40 [INVOKEVIRTUAL] (EnforcedDrawingAreaGraphics.java:347)
    at uSpriteCanvas.copyArea:(IIIIII)V @ 429 [INVOKEVIRTUAL] (null:-1)
    at Game.upaint:(Ljavax/microedition/lcdui/Graphics;)V @ 2803 [INVOKEVIRTUAL] (null:-1)
    at uSpriteCanvas.paint:(Ljavax/microedition/lcdui/Graphics;)V @ 22 [INVOKEVIRTUAL] (null:-1)
    at Game.paint:(Ljavax/microedition/lcdui/Graphics;)V @ 2 [INVOKESPECIAL] (null:-1)
    at cc/squirreljme/runtime/lcdui/phoneui/DrawingMethod$2.paint:(Ljavax/microedition/lcdui/Displayable;Lcc/squirreljme/runtime/lcdui/phoneui/State;Ljavax/microedition/lcdui/Graphics;II)V @ 2 [INVOKEVIRTUAL] (DrawingMethod.java:60)
    at cc/squirreljme/runtime/lcdui/phoneui/ActiveDisplay.paint:(Ljavax/microedition/lcdui/Graphics;IIII)V @ 474 [INVOKEVIRTUAL] (ActiveDisplay.java:354)
    at cc/squirreljme/runtime/lcdui/phoneui/NativeUIBackend.paintDisplay:(IIIII)V @ 81 [INVOKEVIRTUAL] (NativeUIBackend.java:277)
    at <guard frame>
```

An image of the screen the game shows:

![image](https://user-images.githubusercontent.com/11927855/65653087-f30f1b80-dfe1-11e9-8ffa-53ddadfca5e9.png)

**Comment by TwoSpacesSG** [comment]
There seemed to have been two versions dumped that were released on phones and seem to correctly specify the CLDC and MIDP versions. These are:

Gradius.jar (SHA1: 2dfaf1351dfe3a115acd3843e80009c0c419b9bc)

Crashes at boot with this error (also affects Zuma by Glu Mobile, but i will make another issue report about that one as well):
```
TD: INCOMPLETE CODE HAS BEEN REACHED:
java version "1.8.0"
SquirrelJME Class Library, Micro Edition (build 0.3.0-tarball)
Java HotSpot(TM) 64-Bit Server VM (build 25.481-b10, mixed mode)
java.lang.Throwable: INCOMPLETE CODE
        at cc.squirreljme.runtime.cldc.debug.Debugging.todo(Debugging.java:278)
        at cc.squirreljme.runtime.cldc.debug.Debugging.todo(Debugging.java:226)
        at javax.microedition.lcdui.Command.getLabel(Command.java:258)
        at b.e(Unknown Source)
        at b.paint(Unknown Source)
        at javax.microedition.lcdui.Canvas.__paint(Canvas.java:1013)
        at javax.microedition.lcdui.__ExecCanvasPaint__.paint(__ExecCanvasPaint__.java:54)
```

Gradius-j2me-motorola-v3.jar (SHA1: ed27bdbba0151b3f54b33cb5c8a7d2e6a7f95eaf)

This one is more specific and related to vendor API implementations from the looks of it.
```
TD: INCOMPLETE CODE HAS BEEN REACHED:
java version "1.8.0"
SquirrelJME Class Library, Micro Edition (build 0.3.0-tarball)
Java HotSpot(TM) 64-Bit Server VM (build 25.481-b10, mixed mode)
java.lang.Throwable: INCOMPLETE CODE
        at cc.squirreljme.runtime.cldc.debug.Debugging.todo(Debugging.java:278)
        at cc.squirreljme.runtime.cldc.debug.Debugging.todo(Debugging.java:226)
        at com.vodafone.v10.system.device.DeviceControl.getDefaultDeviceControl(DeviceControl.java:38)
        at c.<clinit>(Unknown Source)
        at Gradius.<init>(Unknown Source)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at javax.microedition.midlet.__MIDletInterface__.newInstance(__MIDletInterface__.java:100)
        at javax.microedition.midlet.__MIDletInterface__.newInstance(__MIDletInterface__.java:23)
        at cc.squirreljme.runtime.midlet.ApplicationHandler.main(ApplicationHandler.java:192)
        at javax.microedition.midlet.__MainHandler__.main(__MainHandler__.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cc.squirreljme.emulator.EmulatedReflectionShelf.invokeMain(EmulatedReflectionShelf.java:74)
        at cc.squirreljme.jvm.mle.ReflectionShelf.invokeMain(Native Method)
        at cc.squirreljme.emulator.NativeBinding.main(NativeBinding.java:285)
```
