### ISSUE TITLE
LockEmUp has corrupt graphics

### ISSUE THREAD

**Issue by XerTheSquirrel** [SquirrelJME/SquirrelJME#57]
The game LockEmUp has corrupt graphics. This actually might be sub-images being placed from incorrectly for tiling and such.

Sha1sum: `88226105346bb606aa3a380b27d6432833fa278c  bins/bbld/lockemup.jar`

![image](https://user-images.githubusercontent.com/11927855/65838785-bccce700-e2d4-11e9-8fe0-7dab9817b291.png)
![image](https://user-images.githubusercontent.com/11927855/65838786-be96aa80-e2d4-11e9-82c5-d29f67c6cb5d.png)

**Comment by TwoSpacesSG** [comment]
Currently looking at the existing compatibility issue reports before opening any new ones.
It's possible that the tiling issue may have been fixed by this point, but now the aforementioned LockEmUp (Motorola A008) crashes at boot instead with the message:
```
TD: INCOMPLETE CODE HAS BEEN REACHED:
java version "1.8.0"
SquirrelJME Class Library, Micro Edition (build 0.3.0-tarball)
Java HotSpot(TM) 64-Bit Server VM (build 25.481-b10, mixed mode)
java.lang.Throwable: INCOMPLETE CODE
        at cc.squirreljme.runtime.cldc.debug.Debugging.todo(Debugging.java:278)
        at cc.squirreljme.runtime.cldc.debug.Debugging.todo(Debugging.java:226)
        at javax.microedition.lcdui.Font.charsWidth(Font.java:210)
        at LockEmUp.TitleScreen.paint(TitleScreen.java:58)
        at javax.microedition.lcdui.Canvas.__paint(Canvas.java:1013)
        at javax.microedition.lcdui.__ExecCanvasPaint__.paint(__ExecCanvasPaint__.java:54)
```
It's also worth mentioning that there is another version of this game, for the Nokia 3410 (SHA1: d44355fb423e86e2ac89e3f67558508444c9e34d) which starts, but then shortly after it hangs with the game window "not responding", and "TD: Vibration?" being constantly printed. I am not entirely sure if the window would start responding after any amount of time (on Hosted) like some other games, or not.

**Comment by XerTheSquirrel** [comment]
I never actually got around to implementing `charsWidth()`, so the latest incoming should be getting that in soon. I would like to know if the original graphics issues have been fixed however.
