### ISSUE TITLE
Antilly does not render anything

### ISSUE THREAD

**Issue by XerTheSquirrel** [SquirrelJME/SquirrelJME#9]
Antilly does not render anything (blank screen) and the draw routine just throws `NullPointerException`.

Seen in fossil `39a60ad562382d3169155a7c06f9dcd2644ef1d7`.

Technical:

Antilly stores pre-cached Images into `static Image[] b.q` which is initialized in `b()`. `b()` loads an input stream which also contains image data contained within it in with `DataInputStream`. It will load a chunk of data from the stream then will call `Image.createImage(byte[], int, int)`. This loads an image which is then returned and then stored into the array. The `paint(Graphics)` method calls `b.c(int)` which just returns an index from the static array `Image[] q` which is in class `b`.

It is possible the stream `DataInputStream` reads from has a flaw (possible resources maybe high bytes are handled incorrectly?), the constructor is never properly called, or something is missing in the JAR.

Stack trace as follows:

```
java.lang.NullPointerException: BK2l
  at java/lang/Exception.<init>:(Ljava/lang/String;)V @2 (Exception.java:40)
  at java/lang/RuntimeException.<init>:(Ljava/lang/String;)V @2 (RuntimeException.java:39)
  at java/lang/NullPointerException.<init>:(Ljava/lang/String;)V @2 (NullPointerException.java:38)
  at d.paint:(Ljavax/microedition/lcdui/Graphics;)V @49 (JAX:-1)
  at javax/microedition/lcdui/Canvas.__draw:(Lcc/squirreljme/runtime/lcdui/ui/UIPersist;Lcc/squirreljme/runtime/lcdui/ui/UIStack;Lcc/squirreljme/runtime/lcdui/ui/UIStack;Ljavax/microedition/lcdui/Graphics;)V @76 (Canvas.java:705)
  at javax/microedition/lcdui/__LCDUIProbe__.draw:(Lcc/squirreljme/runtime/lcdui/ui/UIDrawable;Lcc/squirreljme/runtime/lcdui/ui/UIPersist;Lcc/squirreljme/runtime/lcdui/ui/UIStack;Lcc/squirreljme/runtime/lcdui/ui/UIStack;Ljavax/microedition/lcdui/Graphics;)V @10 (__LCDUIProbe__.java:35)
  at cc/squirreljme/runtime/lcdui/ui/UIStack.render:(Lcc/squirreljme/runtime/lcdui/ui/UIPersist;Lcc/squirreljme/runtime/lcdui/ui/UIStack;Ljavax/microedition/lcdui/Graphics;)V @285 (UIStack.java:261)
  at cc/squirreljme/runtime/lcdui/ui/UIStack.render:(Lcc/squirreljme/runtime/lcdui/ui/UIPersist;Lcc/squirreljme/runtime/lcdui/ui/UIStack;Ljavax/microedition/lcdui/Graphics;)V @296 (UIStack.java:267)
  at javax/microedition/lcdui/Display.__doRepaint:(IIII)V @76 (Display.java:1229)
  at javax/microedition/lcdui/__EventCallback__.paintDisplay:(IIIII)V @10 (__EventCallback__.java:109)
  at <unknown>.<unknown> @0
```

**Comment by XerTheSquirrel** [comment]
This is caused by:

```
java.lang.IllegalArgumentException: EB1v
        at javax.microedition.lcdui.Image.createImage(Image.java:301)
        at b.<init>(JAX)
        at antilly.Antilly.<init>(JAX)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at cc.squirreljme.runtime.javase.Main.main(Main.java:188)
Caused by: java.io.IOException: EB34 84
        at cc.squirreljme.runtime.lcdui.image.PNGReader.__unfilter(PNGReader.java:643)
        at cc.squirreljme.runtime.lcdui.image.PNGReader.parse(PNGReader.java:249)
        at cc.squirreljme.runtime.lcdui.image.ImageReaderDispatcher.parse(ImageReaderDispatcher.java:67)
        at javax.microedition.lcdui.Image.createImage(Image.java:369)
        at javax.microedition.lcdui.Image.createImage(Image.java:295)
        ... 8 more
```

**Comment by XerTheSquirrel** [comment]
Antilly is a monochrome game, so it is likely that the scanline length is incorrect. I do `width * ((channels * bitdepth) / 8)` which loses the precision of the width and such for any bit-depth below 8.

**Comment by XerTheSquirrel** [comment]
A more defined error from SpringCoat.

```
java.lang.IllegalArgumentException: EB1v
  at java/lang/Exception.<init>:(Ljava/lang/String;Ljava/lang/Throwable;)V @3 (Exception.java:52)
  at java/lang/RuntimeException.<init>:(Ljava/lang/String;Ljava/lang/Throwable;)V @3 (RuntimeException.java:51)
  at java/lang/IllegalArgumentException.<init>:(Ljava/lang/String;Ljava/lang/Throwable;)V @3 (IllegalArgumentException.java:50)
  at javax/microedition/lcdui/Image.createImage:([BII)Ljavax/microedition/lcdui/Image; @36 (Image.java:301)
  at b.<init>:()V @118 (JAX:-1)
  at antilly/Antilly.<init>:()V @23 (JAX:-1)
  at java/lang/Class.__newInstance:()Ljava/lang/Object; @77 (Class.java:466)
  at java/lang/Thread.__start:()V @176 (Thread.java:749)
  Caused by:java.io.IOException: EB34 84 (0, 4) 19 [78, 60]
    at java/lang/Exception.<init>:(Ljava/lang/String;)V @2 (Exception.java:40)
    at java/io/IOException.<init>:(Ljava/lang/String;)V @2 (IOException.java:38)
    at cc/squirreljme/runtime/lcdui/image/PNGReader.__unfilter:(Ljava/io/InputStream;)[B @124 (PNGReader.java:644)
    at cc/squirreljme/runtime/lcdui/image/PNGReader.parse:()Ljavax/microedition/lcdui/Image; @635 (PNGReader.java:249)
    at cc/squirreljme/runtime/lcdui/image/ImageReaderDispatcher.parse:(Ljava/io/InputStream;)Ljavax/microedition/lcdui/Image; @98 (ImageReaderDispatcher.java:67)
    at javax/microedition/lcdui/Image.createImage:(Ljava/io/InputStream;)Ljavax/microedition/lcdui/Image; @22 (Image.java:369)
    at javax/microedition/lcdui/Image.createImage:([BII)Ljavax/microedition/lcdui/Image; @24 (Image.java:295)
    at b.<init>:()V @118 (JAX:-1)
    at antilly/Antilly.<init>:()V @23 (JAX:-1)
    at java/lang/Class.__newInstance:()Ljava/lang/Object; @77 (Class.java:466)
    at java/lang/Thread.__start:()V @176 (Thread.java:749)
```

**Comment by XerTheSquirrel** [comment]
Fixed this by doing `+ 7` before diving by 8 so the padding in the scanlines exist.
